### PR TITLE
Update Index.js to emit Error Events

### PR DESCRIPTION
**Pull request by RyGuy88228**
Should fix Issue #23 , good luck with your bot!

### CODE REVIEW

**Comment by jdotrjs** [comment]
eep. I wanted to test this before merging it but need to actually roll it out and wait until the bot dies again ... which I forgot to do. 

I'm a bit worried that this will log the error but not re-initiate the connection to the discord server; I think we may need to drop a new `discordClient.login(cfg.discord.token)` call in the error handling function but will have to poke at the API to verify. About to head to bed tonight but will update this ticket as I progress on getting this version rolled out for testing.

@RyGuy88228, thanks so much for making this PR. If you have an answer to my questions that'd be super neat since it sounds like you've already looked into this kind of issue with bots :)

**Comment by jdotrjs** [comment]
New version deployed; now we just need to

1. wait until it dies
2. observe behavior
3. merge or make changes as a result

**Comment by RyGuy88228** [comment]
@jdotrjs Look into [Client#destroy](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=destroy) and [Client#login](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=login), however catching these errors should mean that your bot should not go down, so it's connection will not need to be re-initialized

**Comment by jdotrjs** [comment]
Per comments in the bug we don't crash as a result of errors which is great. This means that the oncall/offcall management stuff still works but the issue marking does not. I assume that this is because we don't reestablish the websocket connection.

I'm going to merge this as it's a significant improvement over the behavior on master but will leave the underlying issue open.

@RyGuy88228, Thanks for the PR! It was annoying to have to reset the server every time this happened so I'm glad that we're half way to fixed now :grinning:

**Pull request merged**
